export const ROUTES = {
  auth: {
    root: "/auth",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
  },
  admin: {
    root: "/admin",
    dashboard: "/admin/dashboard",
    employees: "/admin/employees",
    employeeDetail: (id: string) => `/admin/employees/${id}`,
    departments: "/admin/departments",
    leaveRequests: "/admin/leave-requests",
    attendance: "/admin/attendance",
    attendanceDetail: (id: string) => `/admin/attendance/${id}`,
    officeLocation: "/admin/office-location",
    access: "/admin/access",
    holidays: "/admin/holidays",
    weekOff: "/admin/weekoff",
    leaveAllocation: "/admin/leave-allocation",
    supportTickets: "/admin/support-tickets",
  },
  owner: {
    root: "/owner",
    dashboard: "/owner/dashboard",
    companies: "/owner/companies",
    companyDetail: (id: string) => `/owner/companies/${id}`,
    createCompany: "/owner/companies/create",
    companyAdmins: (id: string) => `/owner/companies/${id}/admins`,
    billing: "/owner/billing",
    plans: "/owner/plans",
    support: "/owner/support",
    settings: "/owner/settings",
    invoiceTemplate: "/owner/settings/invoice-template",
  },
  employee: {
    root: "/employee",
    dashboard: "/employee/dashboard",
    attendance: "/employee/attendance",
    leave: "/employee/leave",
    holidays: "/employee/holidays",
    profile: "/employee/profile",
  },
} as const;
