
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL 
const SESSION_TIMEOUT_MINUTES: number =
  Number(import.meta.env.VITE_SESSION_TIMEOUT_MINUTES) || 30
const SESSION_TIMEOUT_MS = SESSION_TIMEOUT_MINUTES * 60 * 1000


export {  API_BASE_URL, SESSION_TIMEOUT_MINUTES, SESSION_TIMEOUT_MS };
